Add collection view for top games
dtci-ios/dtci-training-ios pull request #10
Opened 2019-09-26 18:38 UTC by rodrigocian

* Implemented CollectionView for Top Games 
![Screen Shot 2019-09-26 at 15 33 41](https://user-images.githubusercontent.com/55462931/65715532-a83de400-e073-11e9-93fc-699804062618.png)
using Api for images

2019-09-30 18:55 UTC, ja-gutierrez requested changes

2019-09-30 18:55 UTC, ja-gutierrez commented on VideoStreaming/GameCollectionViewCell.swift
> +    var game: Game? {
Falta considerar el caso en que Game sea nil. Aquí debería dejar la celda limpia.

2019-09-30 18:55 UTC, ja-gutierrez commented on VideoStreaming/GameCollectionViewCell.swift
> +        gameImageView.image = UIImage(named: Constants.noImage)
Aquí se podría setear game como nil y con el cambio anterior ya saldría.

2019-09-30 18:55 UTC, ja-gutierrez commented on VideoStreaming/GameCollectionViewCell.swift
> +    @IBOutlet weak var gameImageView: UIImageView!
private

2019-09-30 18:55 UTC, ja-gutierrez commented on VideoStreaming/TopGamesCollectionViewController.swift
> +        showHUD()
Usualmente es preferible dejar que se configure la clase base primero antes de hacer nuestras configuraciones. Ponerlo despuees del super.

2019-09-30 18:55 UTC, ja-gutierrez commented on VideoStreaming/TopGamesCollectionViewController.swift
> +    var games : [Game?] = []
Esto no sería para hacerlo como parte de este ticket y creería que le correspondería a @naglotubant . Pero un arreglo de Game opcionales no me suena, debería ser solo un arreglo de Game, yo creo que esto está así por como viene del NetworkManager, pero creo que eso sería bueno arreglarlo. No aquí, ;)

2019-09-30 18:55 UTC, ja-gutierrez commented on VideoStreaming/TopGamesCollectionViewController.swift
> +        TopGamesAPI().fetchTopGames { (retrievedTopGames) in
Este API, sería bueno injectarlo, no usarlo aquí directamente.

2019-09-30 18:55 UTC, ja-gutierrez commented on VideoStreaming/TopGamesCollectionViewController.swift
> +                self.games.append(contentsOf: unRetrivedTopGames)
Aquí se deberían setear los games, no hacerle un append.

2019-09-30 18:55 UTC, ja-gutierrez commented on VideoStreaming/GameCollectionViewCell.swift
> +        static let nibName = "GameCollectionViewCell"
Aquí sería bueno usar la forma de obtener el nombre usando el tipo, de esa forma, si el nombre de la clase cambiara, no habría que modificar este nombre manualmente.

2019-09-30 18:55 UTC, ja-gutierrez commented on VideoStreaming/GameCollectionViewCell.swift
> +        static let reuseIdentifier = "gameCell"
Esto es solo una recomendación, el reuseIdentifier puede ser cualquier cosa, contal que sea único. Usualmente lo que se hace es usar como reuseIdentifier el mismo nombre de la clase, ;)

2019-09-30 19:35 UTC, rodrigocian commented on VideoStreaming/GameCollectionViewCell.swift
> +        static let reuseIdentifier = "gameCell"
Done.

2019-09-30 19:35 UTC, rodrigocian commented on VideoStreaming/GameCollectionViewCell.swift
> +        static let nibName = "GameCollectionViewCell"
Done.

2019-09-30 19:35 UTC, rodrigocian commented on VideoStreaming/TopGamesCollectionViewController.swift
> +        showHUD()
Done.

2019-09-30 19:35 UTC, rodrigocian commented on VideoStreaming/GameCollectionViewCell.swift
> +    @IBOutlet weak var gameImageView: UIImageView!
Done.

2019-09-30 19:35 UTC, rodrigocian commented on VideoStreaming/GameCollectionViewCell.swift
> +        gameImageView.image = UIImage(named: Constants.noImage)
Done.

2019-09-30 19:35 UTC, rodrigocian commented on VideoStreaming/GameCollectionViewCell.swift
> +    var game: Game? {
Done.

2019-09-30 19:45 UTC, rodrigocian commented on VideoStreaming/TopGamesCollectionViewController.swift
> +        TopGamesAPI().fetchTopGames { (retrievedTopGames) in
@ja-gutierrez 
Debiera existir el metodo `setNetWorkingAPI(with: TopGamesAPI())` ?
dicho metodo se llamaria dentro de `viewDidLoad()`no?
TopGames debiera ser un singleton?

2019-09-30 21:32 UTC, ja-gutierrez requested changes

2019-09-30 21:32 UTC, ja-gutierrez commented on VideoStreaming/TopGamesCollectionViewController.swift
> +        TopGamesAPI().fetchTopGames { (retrievedTopGames) in
Hay tres formas de injectar dependencias a una clase. Una es a través del initializer de la clase, otra es dejando las propiedades públicas y setearlas después de instancear la clase o la otra a través de una función. Personalmente, prefiero hacer la injection en ese orden, por initializer si se puede (en algunos casos no aplica), sino por property y como último recurso con un método. Otra cosa es que la dependencía deberia ser una abstración (Protocolo), y ya el encargado de injectar la dependencia le injecta un tipo concreto. Aquí la parte de los nombres es la que enreda un poco, pero por facilidad puedes tener un protocolo TopGamesAPIProtocol. Esto es muy importante porque de esa manera se puede mockear fácilmente el topgames api, y así se poder aplicar los unit tests. O por ejemplo, al principio cuando no teniamos todavía servicios, podríamos haber construido un TopGamesAPIMock devolviendo unos valores quedamos, y así no haber quemado los valores dentro de la clase, ;) @naglotubant @collection-man-globerskin  @rodrigocian

2019-09-30 21:32 UTC, ja-gutierrez commented on VideoStreaming/TopGamesCollectionViewController.swift
> +        }
Recuerden los espacios, pareciera una bobada, pero hace el código más legible, ;)

2019-10-01 15:02 UTC, rodrigocian commented on VideoStreaming/TopGamesCollectionViewController.swift
> +                self.games.append(contentsOf: unRetrivedTopGames)
Done.

2019-10-01 15:03 UTC, rodrigocian commented on VideoStreaming/TopGamesCollectionViewController.swift
> +    var games : [Game?] = []
Bien, lo dejo para luego mergear con el branch de @naglotubant.

2019-10-01 15:03 UTC, rodrigocian commented on VideoStreaming/TopGamesCollectionViewController.swift
> +        TopGamesAPI().fetchTopGames { (retrievedTopGames) in
Done.

2019-10-01 15:19 UTC, ja-gutierrez requested changes

2019-10-01 15:19 UTC, ja-gutierrez commented on VideoStreaming/TopGamesCollectionViewController.swift
> +
Y estos espacios, que fue?, ;)

2019-10-01 15:19 UTC, ja-gutierrez commented on VideoStreaming/TopGamesCollectionViewController.swift
> +        return String(describing: TopGamesCollectionViewController.self)
con self es suficiente, ;)

2019-10-01 15:19 UTC, ja-gutierrez commented on VideoStreaming/TopGamesCollectionViewController.swift
> +
más espacios?, ;)

2019-10-01 15:19 UTC, ja-gutierrez commented on VideoStreaming/TopGamesCollectionViewController.swift
> +
Creo que ya entendí, jaja. Los espacios serían antes del return, y solo en los casos en donde el return no es la única línea de código dentro de un scope. En estos casos no sería necesario el espacio, ;). Sorry si no me hice entender.

2019-10-01 15:19 UTC, ja-gutierrez commented on VideoStreaming/TopGamesCollectionViewController.swift
> +
Por ejemplo aquí si sería un espacio pero antes del return.

2019-10-01 15:52 UTC, rodrigocian commented on VideoStreaming/TopGamesCollectionViewController.swift
> +
Ahhhh okey, no nos entendimos jaja, listo!

2019-10-01 15:52 UTC, rodrigocian commented on VideoStreaming/TopGamesCollectionViewController.swift
> +        return String(describing: TopGamesCollectionViewController.self)
Claro!

2019-10-01 16:05 UTC, ja-gutierrez approved these changes

2019-10-01 19:08 UTC, castadev85 approved these changes

2019-10-01 19:08 UTC, merged