Handle image video cell
dtci-ios/dtci-training-ios pull request #11
Opened 2019-09-26 18:38 UTC by collection-man-globerskin

### **On this PR**

- Fetch image and show it [ ✓ ]
- SDWebImage (Use carthage) [ ✓ ]

![Screen Shot 2019-09-26 at 15 30 01](https://user-images.githubusercontent.com/50028597/65715575-bdb30e00-e073-11e9-9a55-90030eaad06a.png)

2019-09-30 19:20 UTC, ja-gutierrez requested changes

2019-09-30 19:20 UTC, ja-gutierrez commented on VideoStreaming/Models/Video.swift
> +        guard let publishedAtDate = dateFormatter.date(from: publishedAt) else {
Recuerden que es bueno dejar un espacio antes y despues de un modificador de flujo, a menos que esté al principio o al final del scope. También dejar un espacio antes de un return a menos que el return sea la única línea en el scope.

2019-09-30 19:20 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +                self.videos.append(contentsOf: videos)
Aquí se debería setear videos, no hacerle un append.

2019-09-30 19:20 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +    private let videosAPI: VideosAPI = VideosAPI()
Este API debería ser injectado.

2019-09-30 19:20 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +            if let videos = retrievedVideos?.compactMap({ $0 }) {
@naglotubant si haces el cambio del arreglo de opcionalese, este compactMap ya no sería necesario, ;). Te tocaría modificar estos códigos también.

2019-09-30 20:17 UTC, collection-man-globerskin commented on VideoStreaming/Models/Video.swift
> +        guard let publishedAtDate = dateFormatter.date(from: publishedAt) else {
Done

2019-09-30 20:18 UTC, collection-man-globerskin commented on VideoStreaming/VideoPlaylistViewController.swift
> +                self.videos.append(contentsOf: videos)
Done

2019-09-30 20:19 UTC, collection-man-globerskin commented on VideoStreaming/VideoPlaylistViewController.swift
> +    private let videosAPI: VideosAPI = VideosAPI()
Done

2019-09-30 20:21 UTC, naglotubant commented on VideoStreaming/VideoPlaylistViewController.swift
> +            if let videos = retrievedVideos?.compactMap({ $0 }) {
este código aun no esta en master!!! ya cambie lo de los opcionales en un branch aparte

2019-09-30 21:42 UTC, ja-gutierrez requested changes

2019-09-30 21:42 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +        videosAPI = VideosAPI()
Ahí escribí algo en el PR de Rodrigo sobre esto.

2019-09-30 21:42 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
>      var playlist: [Video?] = []
Porque estamos usando dos propiedades que guardan lo mismo?, además, en teoría esta lista no sería un playlist, es una lista de la cual escogemos un video, ;)

2019-10-01 12:26 UTC, collection-man-globerskin commented on VideoStreaming/VideoPlaylistViewController.swift
>      var playlist: [Video?] = []
Listo, ya lo borre

2019-10-01 13:49 UTC, collection-man-globerskin commented on VideoStreaming/VideoPlaylistViewController.swift
> +        videosAPI = VideosAPI()
Ahí estuvimos viendo como inyectarle las dependencias desde un init en este view controller, y ya lo modifique para que tome un VideosAPIProtocol como parámetro cuando se crea

2019-10-01 14:07 UTC, ja-gutierrez requested changes

2019-10-01 14:07 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +    var videosAPI: VideosAPIProtocol?
Esto ya podría ser privado ya que se está injectando en el initializer

2019-10-01 14:07 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +        static let nibName = String(describing: VideoPlaylistViewController.self)
Para este caso en particular, yo les recomendaría en vez de meter este nibName dentro de constants, tener una propiedad computada, de esa forma no tienen que especificar el nombre de la clase sino solo usar `self`, ;)

2019-10-01 14:08 UTC, ja-gutierrez commented
Ahí coloqué unos cambios menores, pero muy bien. Esa es la idea.

2019-10-01 14:14 UTC, collection-man-globerskin commented on VideoStreaming/VideoPlaylistViewController.swift
> +        static let nibName = String(describing: VideoPlaylistViewController.self)
Captado, ahí lo acomodo

2019-10-01 14:51 UTC, ja-gutierrez approved these changes

2019-10-02 15:20 UTC, ja-gutierrez commented
Este PR porque tiene un DO NOT MERGE en el nombre?

2019-10-02 15:30 UTC, collection-man-globerskin commented
@ja-gutierrez esta pr tiene el do not merge porque yo también hice modificaciones en el NetworkManager, tuve que crear una VideosAPI para consultar al endpoint de videos y para que no fuera opcional la respuesta tuve que modificar la función fetchData. Ahora la base de esta branch es CorrectionsOnNetworkManager y debería esperar a que se mergee esa rama para luego cambiar la base a master, no?

2019-10-02 15:41 UTC, ja-gutierrez commented
ahh Vale, no me habia fijado. Gracias. Do Not Merge Label added hasta que el network branch esté mergeado.

2019-10-03 15:01 UTC, castadev85 approved these changes

2019-10-03 15:04 UTC, merged