Added navigation controller
dtci-ios/dtci-training-ios pull request #13
Opened 2019-09-27 20:16 UTC by naglotubant

- If a top game cell is tapped, a list of videos should be pushed showing the videos related to that game. A simple pushed could be used. [ ✓ ]
- It should be done using a UINavigationController and in the list view a navigation bar should be shown with a back button. [ ✓ ]

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/49535765/65799394-69c72880-e14a-11e9-8fc5-54cd67bd075b.gif)

Me faltaría por lo pronto resolver por qué no me muestra la imagen en la celda de la tableview

2019-09-30 14:30 UTC, naglotubant commented
este PR ya incorpora lo que hizo Rodri...

2019-09-30 14:47 UTC, naglotubant commented
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/49535765/65889667-04f11580-e378-11e9-88d4-166bf98b0cf5.gif)

así está ahorita!

2019-09-30 19:30 UTC, ja-gutierrez commented
Añadí el label de `DO NOT MERGE` para que este PR no sea mergeado antes de que se mergeen los cambios de Rodrigo y este PR apunte a master.

2019-09-30 19:31 UTC, ja-gutierrez commented
@naglotubant Al parecer hay algo raro con tus cambios, por que al cambiar la base de este PR a al branch de Rodrigo, deberían solo verse los cambios que hiciste, pero aparecen muchos cambios. Para que porfa revises, ;)

2019-09-30 21:42 UTC, ja-gutierrez commented
@naglotubant  Hay conflictos.

2019-09-30 21:46 UTC, ja-gutierrez commented
Creo que te va tocar volver a hacer los cambios. Porque si te pones a resolver los problemas ya sobre lo que está, creo que te vas a enredar más. Mejor sacar un branch basado en lo que tiene Rodrigo en este momento. y volver a hacer los cambios. Y cada vez que Rodrigo actualice el branch, tu haces un rebase, y así nos enredamos menos. ;)

2019-10-01 16:45 UTC, ja-gutierrez requested changes

2019-10-01 16:45 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +        networkManager.fetchGameStreams(ofGame: gameId ?? "") { (retrievedGameStreamsArray) in
En Swift es muy raro usar las palabras Array o Dictionary al final del nombre de una variable, solo en los casos donde es necesario ponerlos porque de otro modo no se entiende. Ahí del nombre se entiende que son Streams, ;)

2019-10-01 16:45 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +    func setGameIdAndName(gameId: String, gameName: String) {
Que tal si usamos esto en el initializer, pero creo que te toca esperar a que se mergeen los otros cambios primero. ;)

2019-10-01 16:45 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +        networkManager.fetchGameStreams(ofGame: gameId ?? "") { (retrievedGameStreamsArray) in
Si se hace lo de usar el initializer para gameName y gameID ya no sería necesario hacer esta validación ya que no son opcionales, porque si ves, no tiene sentido hacer un fetch si no se tiene un gameID

2019-10-01 17:23 UTC, naglotubant commented on VideoStreaming/VideoPlaylistViewController.swift
> +        networkManager.fetchGameStreams(ofGame: gameId ?? "") { (retrievedGameStreamsArray) in
ya la renombre!!!

2019-10-02 13:46 UTC, ja-gutierrez commented
@naglotubant Conflictos

2019-10-02 14:15 UTC, naglotubant commented
@ja-gutierrez listoooo

2019-10-02 15:19 UTC, ja-gutierrez approved these changes

2019-10-02 15:19 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +        networkManager.fetchGameStreams(ofGame: gameId ?? "") { (retrievedGameStreamsArray) in
Hay ya un PR donde se está arreglando esto, toca estar pendiente si hay conflictos para que esto quede bien, ;)

2019-10-02 18:12 UTC, castadev85 approved these changes

2019-10-02 18:12 UTC, merged