Landscape layout for table view
dtci-ios/dtci-training-ios pull request #19
Opened 2019-10-04 16:10 UTC by collection-man-globerskin

### **On this PR**

- Update videoView layout when the device rotates (portrait, landscape)

![Screen Shot 2019-10-04 at 13 09 12](https://user-images.githubusercontent.com/50028597/66222763-45b69a80-e6a8-11e9-8a53-13b0b02a9ca6.png)

![Screen Shot 2019-10-04 at 13 09 45](https://user-images.githubusercontent.com/50028597/66222787-4f400280-e6a8-11e9-9f40-7755fb23beaf.png)

2019-10-04 18:55 UTC, castadev85 approved these changes

2019-10-07 14:19 UTC, ja-gutierrez requested changes

2019-10-07 14:19 UTC, ja-gutierrez commented on VideoStreaming/NibLoadable.swift
> +    static var nibName: String {
Esoo, ahí van viendo ya la necesidad de generalizar esta lógica, muy bien.

2019-10-07 14:19 UTC, ja-gutierrez commented on VideoStreaming/SubViews/Cells/VideoTableViewCell.swift
> +        videoView.widthAnchor.constraint(equalTo: self.widthAnchor).isActive = true
Esto lo podrías hacer directamente en el xib de la celda, ;)

2019-10-07 17:28 UTC, collection-man-globerskin commented on VideoStreaming/SubViews/Cells/VideoTableViewCell.swift
> +        videoView.widthAnchor.constraint(equalTo: self.widthAnchor).isActive = true
Si, de hecho intente eso en un principio, poner que el width del videoView fuera igual al de la celda en el xib. Pero cuando lo corro en el simulador no me lo está tomando

2019-10-07 21:40 UTC, ja-gutierrez commented on VideoStreaming/SubViews/Cells/VideoTableViewCell.swift
> +        videoView.widthAnchor.constraint(equalTo: self.widthAnchor).isActive = true
Noo pero que?, jaja. Esos simuladores de ustedes, jaja. Pero esto si está todavía más raro, porque dices que no te lo toma?, como queda?

2019-10-08 11:43 UTC, collection-man-globerskin commented on VideoStreaming/SubViews/Cells/VideoTableViewCell.swift
> +        videoView.widthAnchor.constraint(equalTo: self.widthAnchor).isActive = true
![Screen Shot 2019-10-08 at 08 38 15](https://user-images.githubusercontent.com/50028597/66392844-63854780-e9a7-11e9-98a4-5c420f8edb8a.png)

Así es como queda, también probe setear la constraint del ancho de la videoView para que fuera igual a la de videoCell, en vez de content view, pero es lo mismo

2019-10-09 14:39 UTC, ja-gutierrez commented
Quedo con la inquietud de ese constraint ahí, pero bueno, jaja.

2019-10-09 14:39 UTC, merged