Streaming URL
dtci-ios/dtci-training-ios pull request #22
Opened 2019-10-09 16:15 UTC by collection-man-globerskin

**On this PR**

- Use the encodedURL to get the M3U file through the endpoint `https://pwn.sh/tools/streamapi.py?url=<EncodedURL>`
- Get the StreamingURLs from the file.

The base of this PR is ImplementAVPlayer 

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/50028597/66499781-d6b9b700-ea96-11e9-926a-2eb640c44f9e.gif)

2019-10-09 18:33 UTC, castadev85 commented on VideoStreaming/VideoPlaylistViewController.swift
> +        Alamofire.request(endpoint, parameters: nil, headers: GameStreamsAPI.headers).responseJSON { (response) in
Esto deberia estar en un API Client como lo hemos hecho con los otros servicios y no aca en el view controller

2019-10-10 14:10 UTC, ja-gutierrez requested changes

2019-10-10 14:10 UTC, ja-gutierrez commented on VideoStreaming/Networking/PwnRenameAPI.swift
> +            do {
Creo que también sería chévere agregarle manejo de errores. Como se hizo en los otros casos.

2019-10-16 14:54 UTC, ja-gutierrez approved these changes

2019-10-21 18:54 UTC, castadev85 approved these changes

2019-10-21 18:54 UTC, merged