Show options list
dtci-ios/dtci-training-ios pull request #23
Opened 2019-10-11 13:11 UTC by collection-man-globerskin

**On this PR**

- Use an action sheet to show different video qualities. [DONE]
- When tapping one of the options show a player. [DONE]

This branch have the StreamingURL as base

![Screen Shot 2019-10-11 at 10 05 05](https://user-images.githubusercontent.com/50028597/66653876-5ec2cc80-ec0f-11e9-95cb-229e2cf49fb4.png)

![Screen Shot 2019-10-11 at 10 06 21](https://user-images.githubusercontent.com/50028597/66653888-684c3480-ec0f-11e9-9266-a929636fa39a.png)

2019-10-16 14:59 UTC, ja-gutierrez requested changes

2019-10-16 14:59 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +                    alert.addAction(UIAlertAction(title: key, style: .default, handler: { (action) in
Este action como no se está usando es bueno colocar un `_`

2019-10-16 14:59 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +                        if let stringURL = urls[key], let m3u8URL = URL(string: stringURL) {
También esta lógica sería bueno sacarla a un método.

2019-10-16 16:03 UTC, collection-man-globerskin commented on VideoStreaming/VideoPlaylistViewController.swift
> +                    alert.addAction(UIAlertAction(title: key, style: .default, handler: { (action) in
Listo

2019-10-16 16:03 UTC, collection-man-globerskin commented on VideoStreaming/VideoPlaylistViewController.swift
> +                        if let stringURL = urls[key], let m3u8URL = URL(string: stringURL) {
Ya lo puse en un método privado del controller

2019-10-21 16:53 UTC, ja-gutierrez requested changes

2019-10-21 16:53 UTC, ja-gutierrez commented on VideoStreaming/Networking/PwnResponseAPI.swift
> +        requestURL = componentsForServiceURL?.url?.absoluteString ?? ""
Mejor usar guard para esto, el request no se debería hacer si no hay url

2019-10-21 16:53 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +        switch result {
Yo creo que estos results deberían ir lo más cercando a el objeto que lo retorna. Creo que queda más claro, porque uno sabe que acaba de hacer una acción y que algo se debe hacer si fue exitoso y otra cosa si hubo un error. Depronto mejor crear dos métodos, uno para cada caso, ;). Se que puede ser confuso, porque pareciera que están haciendo dos cosas, pero si lo ves como que se está manejando el resultado, no como exito y error sale, jeje. Otra recomendación es que en Swift, no se suelen usar las preposiciones como final del nombre de la funcion ex: `getURLsFrom`, sería preferible usarlo `getURLs(from result: ...)`, ;)

2019-10-21 16:53 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +            let alert = UIAlertController(title: "ERROR", message: error.localizedDescription, preferredStyle: .alert)
Este código es el mismo de abajo, calificado para crear un método. ;)

2019-10-21 17:30 UTC, collection-man-globerskin commented on VideoStreaming/Networking/PwnResponseAPI.swift
> +        requestURL = componentsForServiceURL?.url?.absoluteString ?? ""
Done

2019-10-21 17:31 UTC, collection-man-globerskin commented on VideoStreaming/VideoPlaylistViewController.swift
> +        switch result {
Listo, ahí agregue dos nuevos métodos para cada uno de los casos.

2019-10-21 17:31 UTC, collection-man-globerskin commented on VideoStreaming/VideoPlaylistViewController.swift
> +            let alert = UIAlertController(title: "ERROR", message: error.localizedDescription, preferredStyle: .alert)
Listo

2019-10-21 19:37 UTC, ja-gutierrez requested changes

2019-10-21 19:37 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +                let pwnServiceAPI = PwnServiceAPI(userName: self.takeUserLoginName(from: users))
Creo que aquí terminamos haciendo lo mismo, la API no se debería crear si no hay loginName, ;). Debería mostrar un error también para este caso, ;)

2019-10-24 16:21 UTC, ja-gutierrez approved these changes

2019-10-24 16:21 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +                if loginName != "" {
Un comentario menor, aqui creo que puedes usar en vez de diferente a "" isEmpty

2019-10-24 16:51 UTC, collection-man-globerskin commented on VideoStreaming/VideoPlaylistViewController.swift
> +                if loginName != "" {
Listo

2019-10-24 19:01 UTC, castadev85 approved these changes

2019-10-24 19:02 UTC, merged