Video playlist data source tests
dtci-ios/dtci-training-ios pull request #24
Opened 2019-10-14 19:50 UTC by naglotubant

![Screen Shot 2019-10-14 at 16 49 05](https://user-images.githubusercontent.com/49535765/66778614-9d23ea00-eea2-11e9-9fcf-f5af4a07e476.png)

2019-10-16 15:10 UTC, ja-gutierrez requested changes

2019-10-16 15:10 UTC, ja-gutierrez commented on VideoStreaming/Networking/GameStreamsAPI.swift
> +//    var request = "https://api.twitch.tv/helix/sarasaaa"
Recuerden comments de este tipo mejor no tenerlos.

2019-10-16 15:10 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistDataSource.swift
> +    private var streams: [Stream?] = []
Este arreglo de String opcionales creo que se puede arreglar. No deberían ser opcionales.

2019-10-16 15:10 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistDataSource.swift
> +    private let apiManager: GameStreamsAPIProtocol!
No es necesario definirlo como implicitly unwrapping porque se está seteando en el init.

2019-10-16 15:10 UTC, ja-gutierrez commented on VideoStreaming/VideosAPI.swift
> +//protocol VideosAPIProtocol {
??

2019-10-16 15:10 UTC, ja-gutierrez commented on VideoStreamingTests/VideoPlaylistDataSourceTests.swift
> +        tableView = UITableView()
Creo que mejor lo hablamos a las 2, ;). Acá estamos metiendo cosas de UI, y creo que no deberíamos.

2019-10-16 15:47 UTC, naglotubant commented on VideoStreaming/VideosAPI.swift
> +//protocol VideosAPIProtocol {
@ja-gutierrez esta clase esta dando vueltas hace rato, creo que la creó Juli y no sé si el la estará usando asquee no la borro por eso

2019-10-16 15:52 UTC, naglotubant commented on VideoStreamingTests/VideoPlaylistDataSourceTests.swift
> +        tableView = UITableView()
@ja-gutierrez dale, lo hablamos en la daily, por lo pronto corregí lo otro que me comentaste y agregue algunos test para las funciones CRUD del DataSource

2019-10-16 15:55 UTC, naglotubant commented
![Screen Shot 2019-10-16 at 12 44 39](https://user-images.githubusercontent.com/49535765/66936481-2a3a8080-f014-11e9-839c-5b5225692c4f.png)
![Screen Shot 2019-10-16 at 12 45 07](https://user-images.githubusercontent.com/49535765/66936484-2a3a8080-f014-11e9-94cf-3380beaadc12.png)
![Screen Shot 2019-10-16 at 12 45 23](https://user-images.githubusercontent.com/49535765/66936485-2a3a8080-f014-11e9-8d75-dd7ded211584.png)

2019-10-17 17:53 UTC, naglotubant commented
![Screen Shot 2019-10-17 at 14 33 24](https://user-images.githubusercontent.com/49535765/67034306-d13f1b00-f0ed-11e9-8cbe-45623c9cb4a0.png)
![Screen Shot 2019-10-17 at 14 51 49](https://user-images.githubusercontent.com/49535765/67034307-d1d7b180-f0ed-11e9-98de-16c831f27eed.png)

2019-10-17 18:56 UTC, ja-gutierrez requested changes

2019-10-17 18:56 UTC, ja-gutierrez commented on VideoStreaming/Networking/NetworkManager.swift
> +//    var sessionManager: SessionManager { get set }
??, hehe.

2019-10-17 18:56 UTC, ja-gutierrez commented on VideoStreaming/SubViews/Views/VideoView.swift
> +    private var stream: Stream?
Para que necesitamos esto?

2019-10-17 18:56 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistDataSource.swift
> +    func load(completionForView: @escaping (APIError?) -> Void) {
aquí con dejar completion solamente, creo que queda mejor, ;)

2019-10-17 18:56 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +        guard let filePath = Bundle.main.path(forResource: "lol", ofType: ".mp4") else { return }
Estos cambios creo que no se deberían ver

2019-10-17 18:56 UTC, ja-gutierrez commented on VideoStreaming/VideosAPI.swift
> +//protocol VideosAPIProtocol {
Pero entonces, dejémosla como está, para que estos cambios no quedeen como tuyo, y tengámoslo en cuenta cuando hagamos el clean.

2019-10-17 18:56 UTC, ja-gutierrez commented on VideoStreaming/VideosAPI.swift
> +//protocol VideosAPIProtocol {
Algo importante para que aprendan es hacer los commits bien divididos por tasks, por ejemplo si creaste un commit para solo comentar este archivo, en este caso, sería muy sencillo decirle que borre ese commit y saldría, porque o sino, queda en la historia como que se comentó y luego se descomentó, jeje. Pa la próxima, ;)

2019-10-17 18:56 UTC, ja-gutierrez commented on VideoStreamingTests/VideoPlaylistDataSourceTests.swift
> +        // where
jeje es when, ;)

2019-10-17 18:56 UTC, ja-gutierrez commented on VideoStreamingTests/VideoPlaylistDataSourceTests.swift
> +        streams.isEmpty ? completion(.failure(.emptyDataArray)) : completion(.success(streams))
Creo que esta validación se podría hacer mejor, que los streams estén vacios no significa que eso sea un error, puede que no haya Streams. Por ejemplo acá se podrían por ejemplo colocar unos ifs o un switch, que dependiendo de una propiedad se haga algo, de esa manera este mock se puede usar para testear todos los casos. Por ejemplo, una propiedad opcional que sea error, y si tienen error debe llamar al completion con el error, si no tiene error debe mandar los streams, algo así, ;)

2019-10-17 18:56 UTC, ja-gutierrez commented on VideoStreamingTests/VideoPlaylistDataSourceTests.swift
> +        streams.isEmpty ? completion(.failure(.emptyDataArray)) : completion(.success(streams))
Otra cosa es que como para medio simular el mismo comportamiento, el completion se debería llamar asíncronamente, ya sea de inmediato o con un delay, ;)

2019-10-17 19:39 UTC, naglotubant commented on VideoStreaming/VideoPlaylistViewController.swift
> +        guard let filePath = Bundle.main.path(forResource: "lol", ofType: ".mp4") else { return }
@ja-gutierrez quizás cuando los devolví a la VC los puse en orden...?

2019-10-17 19:39 UTC, naglotubant commented on VideoStreamingTests/VideoPlaylistDataSourceTests.swift
> +        // where
@ja-gutierrez okiiii je

2019-10-17 19:49 UTC, naglotubant commented on VideoStreamingTests/VideoPlaylistDataSourceTests.swift
> +        streams.isEmpty ? completion(.failure(.emptyDataArray)) : completion(.success(streams))
@ja-gutierrez no me queda muy claro lo de "una propiedad opcional que sea error"... podrías mostrarme?

2019-10-21 19:27 UTC, ja-gutierrez requested changes

2019-10-21 19:27 UTC, ja-gutierrez commented on VideoStreaming/SubViews/Cells/VideoTableViewCell.swift
> +    var videoId: String?
Esto lo necesitamos?

2019-10-21 19:27 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistDataSource.swift
> +    func getStreamCount() -> Int {
Creo que quedaría mejor haciendo esto una propiedad computade en vez de un método, ;)

2019-10-21 19:27 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +    private var apiError: APIError?
y esta propiedad?, si la necesitamos?

2019-10-21 19:27 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +        guard let filePath = Bundle.main.path(forResource: "lol", ofType: ".mp4") else { return }
Es que creo que esto ya lo está modificando Julian, yo creo que van a ver conflictos. ;)

2019-10-21 19:27 UTC, ja-gutierrez commented on VideoStreaming/VideosAPI.swift
> +//protocol VideosAPIProtocol {
Sigo viendo estos cambios, :(

2019-10-21 19:27 UTC, ja-gutierrez commented on VideoStreamingTests/VideoPlaylistDataSourceTests.swift
> +        dataSource = VideoPlaylistDataSource(apiManager: apiManager!, gameId: "")
Creo que se nos fue el `!` despues del apiManager

2019-10-21 19:27 UTC, ja-gutierrez commented on VideoStreamingTests/VideoPlaylistDataSourceTests.swift
> +        XCTAssertNil(completionError)
Este completion siempre va a ser nil en este punto, recuerden lo de la explicación de asíncrono y síncrono. Aunque ya veo que es lo que está pasando. Natu, recuerda lo de en el mock tener una respuesta asíncrona, esto está funcionando solo por eso, jeje. Si colocas en el mock que llame al complation en un dispatch.async ya te va a fallar, y la verdad ese es el caso real., ;)

2019-10-21 19:46 UTC, naglotubant commented on VideoStreaming/SubViews/Cells/VideoTableViewCell.swift
> +    var videoId: String?
no :)

2019-10-21 19:46 UTC, naglotubant commented on VideoStreaming/VideoPlaylistDataSource.swift
> +    func getStreamCount() -> Int {
oki

2019-10-21 19:53 UTC, naglotubant commented on VideoStreaming/VideoPlaylistViewController.swift
> +    private var apiError: APIError?
no :)

2019-10-21 20:15 UTC, naglotubant commented on VideoStreamingTests/VideoPlaylistDataSourceTests.swift
> +        XCTAssertNil(completionError)
creo que ahi lo solucioné...

2019-10-21 20:20 UTC, rodrigocian commented on VideoStreaming/VideoPlaylistDataSource.swift
> +    func getStreamCount() -> Int {
Tomo este mismo comentario para hacer una corrección en la PR de TopGames.

2019-10-21 20:49 UTC, rodrigocian commented on VideoStreamingTests/VideoPlaylistDataSourceTests.swift
> +        XCTAssertNil(completionError)
Tomo este mismo comentario para hacer una corrección en la PR de TopGames.

2019-10-22 22:05 UTC, ja-gutierrez requested changes

2019-10-22 22:05 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistDataSource.swift
> +        return (streamCount == 0 && gameId == nil) ? true : false
Creo que puedes remover esto ` ? true : false` y los paréntesis también, ;)

2019-10-22 22:05 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistDataSource.swift
> +        if let i = containsStream(withId: streamId) {
Se que el scope de esta variable i es muy chiquito y fácil se puede deducir de que es un index, pero si lo llamas index no habría que deducir nada, jeje.

2019-10-22 22:05 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistDataSource.swift
> +        if let i = containsStream(withId: streamId) {
la otra sería el nombre de esta función. Si ves, esta está como diciendo si contiene un Stream, pero en realidad está es pidiendo un index.

2019-10-22 22:05 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
>      private var gameId: String?
Creo que ya hay unas propiedades que ya no aplican, por ejemplo gamiID

2019-10-23 14:48 UTC, naglotubant commented on VideoStreaming/VideoPlaylistDataSource.swift
> +        return (streamCount == 0 && gameId == nil) ? true : false
done ;)

2019-10-23 14:48 UTC, naglotubant commented on VideoStreaming/VideoPlaylistDataSource.swift
> +        if let i = containsStream(withId: streamId) {
tiene usted mucha razón!

2019-10-23 14:49 UTC, naglotubant commented on VideoStreaming/VideoPlaylistDataSource.swift
> +        if let i = containsStream(withId: streamId) {
lo cambié a indexOfStream(withId:) ;)

2019-10-23 14:49 UTC, naglotubant commented on VideoStreaming/VideoPlaylistViewController.swift
>      private var gameId: String?
done!

2019-10-24 16:32 UTC, ja-gutierrez requested changes

2019-10-24 16:32 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistDataSource.swift
> +    func getStream(withId streamId: String) -> Stream? {
Perdona que te ponga a hacer esto, jaja. Pero para que lo tengan en cuenta, jeje. Hay veces que uno crea métodos como para decir, chévere tenerlo por si alguien lo usa, pero por experiencia personal es preferible crear una clase solo con lo que realmente se esté usando. Por lo que veo este método no se está usando, por ende sería bueno borrarlo. La otra cosa es que, si hay un método o propiedad que solo la usa la clase, recuerden dejarla privada, eso significa que se evitaran un test también porque no van a tener acceso a esa propiedad, ;)

2019-10-24 16:57 UTC, naglotubant commented on VideoStreaming/VideoPlaylistDataSource.swift
> +    func getStream(withId streamId: String) -> Stream? {
listu

2019-10-24 19:02 UTC, castadev85 approved these changes

2019-10-24 19:10 UTC, ja-gutierrez commented
@naglotubant Conflictos, ;)

2019-10-24 19:14 UTC, ja-gutierrez approved these changes

2019-10-25 15:38 UTC, merged