Add top games data source tests
dtci-ios/dtci-training-ios pull request #25
Opened 2019-10-15 17:10 UTC by rodrigocian

![Screen Shot 2019-10-15 at 14 09 18](https://user-images.githubusercontent.com/55462931/66853344-6b1f9000-ef55-11e9-9e61-bf050d15c8c0.png)

2019-10-16 15:18 UTC, ja-gutierrez requested changes

2019-10-16 15:18 UTC, ja-gutierrez commented on VideoStreaming/TopGamesDataSource.swift
> +    func fetchDataSource(completionForView: @escaping (APIError?) -> Void) {
Creoq que con user `completion` es suficiente, se entiende que es el completion de llamar a fetchDataSource, ;)

2019-10-16 15:18 UTC, ja-gutierrez commented on VideoStreaming/TopGamesDataSource.swift
> +    func fetchDataSource(completionForView: @escaping (APIError?) -> Void) {
Creo que @naglotubant tiene algo parecido en el PR de ella, ;)

2019-10-16 15:18 UTC, ja-gutierrez commented on VideoStreamingTests/TopGamesDataSourceTests.swift
> +    var collectionView: UICollectionView!
Mismo comentario que a Natu, más tarde lo hablamos, ;)

2019-10-16 15:18 UTC, ja-gutierrez commented on VideoStreamingTests/TopGamesDataSourceTests.swift
> +    //testear que no sea nil luego de crear
Recuerden que los comentarios son solo para casos donde realmente son necesarios, donde hay excepciones o lógica que con verla ahí no es fácil de entender (Casos muy raros), ;)

2019-10-16 15:18 UTC, ja-gutierrez commented on VideoStreamingTests/TopGamesDataSourceTests.swift
> +    //testear que no sea nil luego de crear
El mismo nombre del test debería describir que es lo que se está haciendo. ;)

2019-10-16 15:18 UTC, ja-gutierrez commented on VideoStreamingTests/TopGamesDataSourceTests.swift
> +    func testPerformanceExample() {
Esto se puede borrarr, ;)

2019-10-16 17:24 UTC, rodrigocian commented on VideoStreamingTests/TopGamesDataSourceTests.swift
> +    func testPerformanceExample() {
Bien, borrado.

2019-10-16 17:24 UTC, rodrigocian commented on VideoStreamingTests/TopGamesDataSourceTests.swift
> +    //testear que no sea nil luego de crear
okey.

2019-10-21 19:07 UTC, castadev85 approved these changes

2019-10-25 14:50 UTC, ja-gutierrez approved these changes

2019-10-25 14:50 UTC, merged