Implement related videos
dtci-ios/dtci-training-ios pull request #26
Opened 2019-10-21 18:55 UTC by collection-man-globerskin

This branch is a sub-branch of the ShowOptionsList

**On This PR**

- Table view for related videos implemented
- A view with a label for the title of the video
- Quality options for related videos appears when a cell is tapped (as an action sheet)
- A video is played when an option is selected

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/50028597/67234205-19767a00-f41b-11e9-9d83-ef98ac043256.gif)

2019-10-22 14:49 UTC, collection-man-globerskin commented
Support landscape and portrait for video player


![Screen Shot 2019-10-22 at 11 48 36](https://user-images.githubusercontent.com/50028597/67298669-f5ba3f00-f4c1-11e9-8055-bb027f4a0cd2.png)
![Screen Shot 2019-10-22 at 11 48 54](https://user-images.githubusercontent.com/50028597/67298670-f5ba3f00-f4c1-11e9-9863-f8b59a270c22.png)

2019-10-24 19:08 UTC, ja-gutierrez requested changes

2019-10-24 19:08 UTC, ja-gutierrez commented on VideoStreaming/StreamPlayerViewController.swift
> +    override func viewDidLoad() {
faltó llamar al super, ;). Esto puede que haya afectado en algo, jeje.

2019-10-24 19:08 UTC, ja-gutierrez commented on VideoStreaming/StreamPlayerViewController.swift
> +            landscapeVideoView.willMove(toSuperview: view)
Para que estás usando este método?

2019-10-24 19:26 UTC, collection-man-globerskin commented on VideoStreaming/StreamPlayerViewController.swift
> +    override func viewDidLoad() {
Agregado

2019-10-24 19:26 UTC, collection-man-globerskin commented on VideoStreaming/StreamPlayerViewController.swift
> +            landscapeVideoView.willMove(toSuperview: view)
Al final, no hacía falta llamar a ese método. Ya lo quite

2019-10-25 14:56 UTC, ja-gutierrez approved these changes

2019-10-25 14:56 UTC, ja-gutierrez commented on VideoStreaming/SubViews/Cells/VideoTableViewCell.swift
> +        videoView.widthAnchor.constraint(equalTo: self.widthAnchor).isActive = true
Jaja, me sigue sin cuadrar esto, pero bueno, jaja. Pa un futuro.

2019-10-25 15:02 UTC, castadev85 approved these changes

2019-10-25 15:02 UTC, merged