Video table view cell implemented
dtci-ios/dtci-training-ios pull request #3
Opened 2019-09-18 17:50 UTC by collection-man-globerskin

2019-09-19 19:51 UTC, collection-man-globerskin commented
![Screen Shot 2019-09-19 at 16 41 20](https://user-images.githubusercontent.com/50028597/65276277-c51b6a00-dafd-11e9-91aa-5bc47dc7a9ff.png)

2019-09-20 11:43 UTC, collection-man-globerskin commented
![Screen Shot 2019-09-20 at 08 42 54](https://user-images.githubusercontent.com/50028597/65324496-c2168d00-db82-11e9-88c2-7331152e26d7.png)

2019-09-20 21:14 UTC, ja-gutierrez requested changes

2019-09-20 21:14 UTC, ja-gutierrez commented on VideoStreaming/SubViews/Cells/VideoTableViewCell.swift
> +    @IBOutlet private var videoView: VideoView!
weak

2019-09-20 21:14 UTC, ja-gutierrez commented on VideoStreaming/SubViews/Cells/VideoTableViewCell.swift
> +    override func awakeFromNib() {
Esto se puede borrar.

2019-09-20 21:14 UTC, ja-gutierrez commented on VideoStreaming/SubViews/Cells/VideoTableViewCell.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
esto también se puede borrar.

2019-09-20 21:14 UTC, ja-gutierrez commented on VideoStreaming/SubViews/Cells/VideoTableViewCell.swift
> +        self.videoView.configure(with: video)
self no es necesario.

2019-09-20 21:14 UTC, ja-gutierrez commented on VideoStreaming/SubViews/Views/VideoView.swift
> +    @IBOutlet var contentView: UIView!
Faltaron unos private

2019-09-20 21:14 UTC, ja-gutierrez commented on VideoStreaming/SubViews/Views/VideoView.swift
> +        Bundle.main.loadNibNamed(String(describing: VideoView.self), owner: self, options: nil)
Esta lógica tiene algo raro, sería bueno que la revisáramos.

2019-09-20 21:14 UTC, ja-gutierrez commented on VideoStreaming/SubViews/Views/VideoView.swift
> +        self.addSubview(contentView)
self se puede borrar.

2019-09-20 21:14 UTC, ja-gutierrez commented on VideoStreaming/SubViews/Views/VideoView.swift
> +        guard let contentView = contentView else { return }
Este guard no debería ser necesario.

2019-09-20 21:14 UTC, ja-gutierrez commented on VideoStreaming/ViewController.swift
> +        tableView.delegate = self
Yo se que esta clase eventualmente se va a borrar, pero solo para tenerlo en cuenta, también es bueno borrar los comments que coloca por defecto el IDE. ;)

2019-09-23 12:36 UTC, collection-man-globerskin commented on VideoStreaming/SubViews/Cells/VideoTableViewCell.swift
> +    override func awakeFromNib() {
Done

2019-09-23 12:37 UTC, collection-man-globerskin commented on VideoStreaming/SubViews/Cells/VideoTableViewCell.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
Done

2019-09-23 12:37 UTC, collection-man-globerskin commented on VideoStreaming/SubViews/Cells/VideoTableViewCell.swift
> +        self.videoView.configure(with: video)
Done

2019-09-23 12:37 UTC, collection-man-globerskin commented on VideoStreaming/SubViews/Views/VideoView.swift
> +    @IBOutlet var contentView: UIView!
Done

2019-09-23 12:37 UTC, collection-man-globerskin commented on VideoStreaming/SubViews/Views/VideoView.swift
> +        self.addSubview(contentView)
Done

2019-09-23 12:37 UTC, collection-man-globerskin commented on VideoStreaming/ViewController.swift
> +        tableView.delegate = self
Done

2019-09-23 12:37 UTC, collection-man-globerskin commented on VideoStreaming/SubViews/Cells/VideoTableViewCell.swift
> +    @IBOutlet private var videoView: VideoView!
Done

2019-09-23 19:55 UTC, collection-man-globerskin commented on VideoStreaming/SubViews/Views/VideoView.swift
> +        guard let contentView = contentView else { return }
Done

2019-09-23 19:55 UTC, collection-man-globerskin commented on VideoStreaming/SubViews/Views/VideoView.swift
> +        Bundle.main.loadNibNamed(String(describing: VideoView.self), owner: self, options: nil)
Done

2019-09-24 15:16 UTC, ja-gutierrez requested changes

2019-09-24 15:16 UTC, ja-gutierrez commented on VideoStreaming/SubViews/Views/VideoView.swift
> +        videoImageView?.image = UIImage(named: video.imageName)
Estas propiedades están creadas como implicitly unwrapping, por tal motivo no es necesario usar el optional chaining. Otra cosa que veo que falta es tener una manera de limpiar esta view, es decir, que quedé sin nada de información y con el placeholder para que cuando se setee una nueva info cuando esta celda se reuse, no vaya a quedar información vieja de la anterior, es una práctica buena para tener, sin importar que siempre se setten los valores. Puede ser otro método llamado reset, o recibiendo el video como opcional, ya miras cual quedá mejor, yo creo que la del reset me suena más. La otra es que en TableView, no olvides usar el método prepareForReuse, para llamar este método que te hablé, ;)

2019-09-24 15:32 UTC, collection-man-globerskin commented on VideoStreaming/SubViews/Views/VideoView.swift
> +        videoImageView?.image = UIImage(named: video.imageName)
Done

2019-09-24 16:15 UTC, ja-gutierrez requested changes

2019-09-24 16:15 UTC, ja-gutierrez commented on VideoStreaming/ViewController.swift
> +        cell.prepareForReuse()
Esto no es necesario, esto es llamado automáticamente cuando se va a reusar la celda, ;)

2019-09-24 16:16 UTC, ja-gutierrez commented
@collection-man-globerskin tienes conflictos. Toca que actualices el branch que tienes con master.

2019-09-24 17:16 UTC, collection-man-globerskin commented on VideoStreaming/ViewController.swift
> +        cell.prepareForReuse()
Ok, ya lo borre

2019-09-24 19:06 UTC, ja-gutierrez requested changes

2019-09-24 19:06 UTC, ja-gutierrez commented on VideoStreaming/SubViews/Views/VideoView.swift
> +        videoImageView.image = nil
Que pasó con el placeholder?, ;)

2019-09-24 19:40 UTC, collection-man-globerskin commented on VideoStreaming/SubViews/Views/VideoView.swift
> +        videoImageView.image = nil
Done

2019-09-24 21:28 UTC, ja-gutierrez approved these changes

2019-09-24 21:51 UTC, castadev85 approved these changes

2019-09-24 21:51 UTC, merged