Implement loading view using MBProgressHUD
dtci-ios/dtci-training-ios pull request #4
Opened 2019-09-19 13:58 UTC by rodrigocian

## On this PR
--------

* Excecuted 'pod init' command. Added 'MBProgressHUD' to Podfile, Excecuted 'pod install' command.

* Created UIViewController+MBProgressHUD. Created MainViewController for check funcionality of MBProgressHU. Deleted useless ViewController.swift

* Changes on project configs.

## Evidence
--------

![MBProgressHUD480](https://user-images.githubusercontent.com/55462931/65250166-88367f80-dacb-11e9-8c3b-21cdf3d7d101.gif)

## Checklist
--------

- [x] I did add reviewers to this PR

2019-09-20 15:59 UTC, ja-gutierrez requested changes

2019-09-20 15:59 UTC, ja-gutierrez commented on VideoStreaming/MainViewController.swift
> +        //Added asyncAfter on main Queue for see the progressHUD.
Es sola una recomendación, jeje. Yo se que lo hacen con buena intención, jaja. Pero solo debería haber comentarios para clarificar algo excepcional. El solo hecho de leer el código debería ser suficiente, ;). Ahí la razón de hacer API claras, si una clase es clara en su construcción, en su uso no se deberían necesitar comentarios, ;)

2019-09-20 15:59 UTC, ja-gutierrez commented on VideoStreaming/MainViewController.swift
> +        self.showHUD(progressLabel: "Loading...")
este `self` sobra. Solo se deberían usar self si es necesario y el código lo obliga.

2019-09-20 15:59 UTC, ja-gutierrez commented on VideoStreaming/UIViewController+MBProgressHUD.swift
> +        DispatchQueue.main.async{
este Dispatch no sería necesario. Recuerden lo que les explicaba, si por alguna razón esto se llama en un hilo que no es el main, allá es donde deberían llamar este Dispatch, no aquí, ;)

2019-09-20 15:59 UTC, ja-gutierrez commented on VideoStreaming/UIViewController+MBProgressHUD.swift
> +        DispatchQueue.main.async{
Lo mismo aquí.

2019-09-20 17:22 UTC, rodrigocian commented on VideoStreaming/MainViewController.swift
> +        //Added asyncAfter on main Queue for see the progressHUD.
Bien, resuelto.

2019-09-20 17:25 UTC, rodrigocian commented on VideoStreaming/UIViewController+MBProgressHUD.swift
> +        DispatchQueue.main.async{
Resuelto.

2019-09-20 17:25 UTC, rodrigocian commented on VideoStreaming/MainViewController.swift
> +        self.showHUD(progressLabel: "Loading...")
Resuelto.

2019-09-23 16:47 UTC, ja-gutierrez approved these changes

2019-09-25 18:39 UTC, ja-gutierrez commented
@rodrigocian Este Pr tiene conflictos.

2019-09-25 19:23 UTC, castadev85 approved these changes

2019-09-26 14:02 UTC, merged