Video playlist
dtci-ios/dtci-training-ios pull request #5
Opened 2019-09-19 14:35 UTC by naglotubant

- Create UITableView [ ✓ ]
- Implement UITableViewDataSource [ ✓ ]
- Create property with mock data [ ✓ ]
- Implement UITableViewDelegate [ ✓ ]
- Pull to refresh [ ✓ ]
- Use Xib [ ✓ ]

![evidence](https://user-images.githubusercontent.com/49535765/65253711-7b1c8f00-dad1-11e9-90be-5b668c43f5c7.gif)

2019-09-19 15:56 UTC, castadev85 requested changes

2019-09-19 15:56 UTC, castadev85 commented on VideoPlaylistViewController.swift
> +struct Video {
Esto lo podrías mover a un archivo aparte

2019-09-19 15:56 UTC, castadev85 commented on VideoStreaming/VideoPlaylistViewController.swift
> +class VideoPlaylistViewController: UIViewController {
Veo que hay una clase similar a esta en otra parte

2019-09-19 16:07 UTC, naglotubant commented on VideoStreaming/VideoPlaylistViewController.swift
> +class VideoPlaylistViewController: UIViewController {
hola!!! cual sería la clase similar? :)

2019-09-19 16:13 UTC, naglotubant commented on VideoPlaylistViewController.swift
> +struct Video {
hecho

2019-09-19 16:15 UTC, naglotubant commented on VideoStreaming/VideoPlaylistViewController.swift
> +class VideoPlaylistViewController: UIViewController {
en mi Xcode solo me aparece una VideoPlaylistViewController

2019-09-19 16:19 UTC, naglotubant commented on VideoStreaming/VideoPlaylistViewController.swift
> +class VideoPlaylistViewController: UIViewController {
listo ya lo encontre y lo borre

2019-09-19 19:51 UTC, castadev85 approved these changes

2019-09-20 15:51 UTC, ja-gutierrez requested changes

2019-09-20 15:51 UTC, ja-gutierrez commented on VideoStreaming/VideoPlaylistViewController.swift
> +        tableView.register(UINib(nibName: "VideoTableViewCell", bundle: nil), forCellReuseIdentifier: "videoCell")
Algo para tener en cuenta es tratar de colocar todos los strings agrupados o bajao un namespace apropiado. Pro ejemplo, este nombre del `VideoTableViewCell` lo deberías sacar de la celda como tal, al igual que el `videoCell`.
Si fuera una constante para este controlador, se debería agrupar bajo un enum o struct con propiedades estáticas. Algo así: 

```swift
private enum Constants {
        static let videoID = "videoId - testing"
        static let alertID = "alertID - testing"
        static let alertText = "alertText - testing"
    }
```

Para este caso en particular, si esos strings se deberían obtener de la clase en sí.
Algo como: 

```swift
tableView.register(UINib(nibName: VideoTableViewCell.nibName, bundle: nil), forCellReuseIdentifier: VideoTableViewCell.reuseIdentifier)
```

Es más eso se puede hacer de una forma más genérica para todas las celdas, pero eso es harina de otro costal, jaja, ;)

2019-09-20 15:51 UTC, ja-gutierrez commented on VideoStreaming/VideoTableViewCell.swift
> +    @IBOutlet weak var vidImage: UIImageView!
IBOutlets deberían ser privados siempre, ;)

2019-09-20 15:51 UTC, ja-gutierrez commented on VideoStreaming/VideoTableViewCell.swift
> +        vidImage.image = UIImage(named: "Placeholder")
Este sería un caso de lo que expliqué más arriba, ;)

2019-09-23 19:01 UTC, ja-gutierrez approved these changes

2019-09-24 15:17 UTC, merged