Added Alamofire through Carthage
dtci-ios/dtci-training-ios pull request #6
Opened 2019-09-20 20:03 UTC by naglotubant

Alamofire Use Carthage [ ✓ ]

2019-09-20 21:15 UTC, ja-gutierrez commented
Sería chévere tener ya sea un llamado o algo que esté usando de la librería para estar seguros que todo quedó bien, ;)

2019-09-23 19:28 UTC, naglotubant commented
ahi pushié la prueba de Alamofire!!!! Saluditosss

2019-09-24 21:41 UTC, castadev85 requested changes

2019-09-24 21:41 UTC, castadev85 commented on VideoStreaming/NetworkManager.swift
> +class NetworkManager {
Podrías mover esto a un protocolo, algo como 

```
protocol NetworkManager {
      var request: String { get }
      func getData <T:Codable> (request: String, completion: @escaping (([T?]?)->Void))
}

extension NetworkManager {
    // aca pones la implemetacion de getData
}
```

Y luego en otro file podemos crear objetos concretos que conformen ese protocolo

```
class TopGamesAPI: NetworkManager {
    let request: String
   
    init() {
        // aca creas el request especifico para top games
    }

    func getGames (completion:  @escaping (([Game?]?)->Void)) { 
     ......
    }  
}
```

2019-09-25 19:54 UTC, castadev85 approved these changes

2019-09-25 20:11 UTC, ja-gutierrez requested changes

2019-09-25 20:11 UTC, ja-gutierrez commented on VideoStreaming/GameStreamsAPI.swift
> +class GameStreamsAPI : NetworkManager {
Voy a colocar unos comments pero la idea sería para hacerlos despues, ya que necesitamos tener avance. 
Quitar espacio antes de los dos puntos.

2019-09-25 20:11 UTC, ja-gutierrez commented on VideoStreaming/GameStreamsAPI.swift
> +    func fetchGameStreams(ofGame gameId: String = "21779", completion: @escaping ([Stream?]?) -> Void) {
Tengo dudas sobre el arreglol opcional de arreglos, pero despues lo vemos mejor.

2019-09-25 20:11 UTC, ja-gutierrez commented on VideoStreaming/Models.swift
> +struct ReceivedData<T:Codable>: Codable {
Esto todavía no estoy seguro de si sea necesario, despues lo miramos, ;)

2019-09-25 20:11 UTC, ja-gutierrez commented on VideoStreaming/NetworkManager.swift
> +                completion(nil)
FAltaría el manejo de errores.

2019-09-25 20:11 UTC, ja-gutierrez commented on VideoStreaming/TopGamesAPI.swift
> +class TopGamesAPI : NetworkManager {
Espacio aqui también.

2019-09-25 20:11 UTC, ja-gutierrez approved these changes

2019-09-25 20:11 UTC, merged