Requested changes
dtci-ios/dtci-training-ios pull request #7
Opened 2019-09-25 20:50 UTC by naglotubant

2019-09-25 20:59 UTC, naglotubant commented
lo del alert en el manejo de error del JsonDecoder, tendría que importar UIKit al archivo... asique lo dejé así simple con el print(), pero si no es problema lo implemento... no estoy segura si da para importar cosas de UI en un archivo de networking

2019-09-25 21:06 UTC, ja-gutierrez requested changes

2019-09-25 21:06 UTC, ja-gutierrez commented on VideoStreaming/Networking/NetworkManager.swift
> +                guard let arr = gamesResponse.dataArr else {
Usualmente en swift es muy raro usar abreviaciones, es preferible tener un nombre muy largo pero que se entienda de una cuando uno lee el código. Por ejemplo el arr y el dataArr.

2019-09-25 21:07 UTC, ja-gutierrez commented
Por ahora el print está bien.

2019-09-26 14:01 UTC, ja-gutierrez approved these changes

2019-09-26 14:39 UTC, castadev85 approved these changes

2019-09-26 14:39 UTC, merged